# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  #  telstra_messaging_api client class.
  class TelstraMessagingApiClient
    # Singleton access to provisioning controller.
    # @return [ProvisioningController] Returns the controller instance.
    def provisioning
      ProvisioningController.instance
    end

    # Singleton access to messaging controller.
    # @return [MessagingController] Returns the controller instance.
    def messaging
      MessagingController.instance
    end

    # Singleton access to o_auth_authorization controller.
    # @return [OAuthAuthorizationController] Returns the controller instance.
    def o_auth_authorization
      OAuthAuthorizationController.instance
    end

    # Returns the configuration class for easy access.
    # @return [Configuration] Returns the actual configuration class.
    def config
      Configuration
    end

    # Returns the authentication class for easy access.
    # @return [OAuth2] Returns the actual OAuth2 class.
    def auth
      OAuth2
    end

    # Initializer with authentication and configuration parameters.
    def initialize(o_auth_client_id: nil, o_auth_client_secret: nil)
      Configuration.o_auth_client_id = o_auth_client_id if
        o_auth_client_id
      Configuration.o_auth_client_secret = o_auth_client_secret if
        o_auth_client_secret
    end
  end
end
