=begin
#Telstra Messaging API

#The Telstra Messaging API specification

The version of the OpenAPI document: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'date'

module Telstra_Messaging
  class Status
    PEND = "PEND".freeze
    SENT = "SENT".freeze
    DELIVRD = "DELIVRD".freeze
    EXPIRED = "EXPIRED".freeze
    DELETED = "DELETED".freeze
    UNDVBL = "UNDVBL".freeze
    REJECTD = "REJECTD".freeze
    UNKNOWN = "Unknown".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = Status.constants.select { |c| Status::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #Status" if constantValues.empty?
      value
    end
  end
end
