# -*- encoding: utf-8 -*-

=begin
#Telstra Messaging API

#The Telstra Messaging API specification

The version of the OpenAPI document: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

$:.push File.expand_path("../lib", __FILE__)
require "Telstra_Messaging/version"

Gem::Specification.new do |s|
  s.name        = "Telstra_Messaging"
  s.version     = Telstra_Messaging::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Telstra"]
  s.email       = [""]
  s.homepage    = "https://dev.telstra.com"
  s.summary     = "Telstra Messaging API Ruby Gem"
  s.description = "The Telstra Messaging API specification"
  s.license     = 'Apache-2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
