=begin
#Telstra Messaging API

# The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 

OpenAPI spec version: 2.2.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'

# Unit tests for Telstra_Messaging::ProvisioningApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProvisioningApi' do
  before do
    # run before each test
    @instance = Telstra_Messaging::ProvisioningApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProvisioningApi' do
    it 'should create an instance of ProvisioningApi' do
      expect(@instance).to be_instance_of(Telstra_Messaging::ProvisioningApi)
    end
  end

  # unit tests for create_subscription
  # Create Subscription
  # Provision a mobile number
  # @param authorization An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.
  # @param body A JSON payload containing the required attributes
  # @param [Hash] opts the optional parameters
  # @return [ProvisionNumberResponse]
  describe 'create_subscription test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_subscription
  # Delete Subscription
  # Delete a mobile number subscription from an account
  # @param authorization An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_subscription test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_subscription
  # Get Subscription
  # Get mobile number subscription for an account
  # @param authorization An OAUTH bearer token that is entitled to use the &#39;SUBSCRIPTION&#39; scope.
  # @param [Hash] opts the optional parameters
  # @return [Array<ProvisionNumberResponse>]
  describe 'get_subscription test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
