=begin
#Telstra Messaging API

# The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 

OpenAPI spec version: 2.2.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Telstra_Messaging::MessageType
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MessageType' do
  before do
    # run before each test
    @instance = Telstra_Messaging::MessageType.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessageType' do
    it 'should create an instance of MessageType' do
      expect(@instance).to be_instance_of(Telstra_Messaging::MessageType)
    end
  end
end

