=begin
#Telstra Messaging API

#The Telstra Messaging API specification

The version of the OpenAPI document: 2.2.9

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3-SNAPSHOT

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Telstra_Messaging::ProvisionNumberResponse
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProvisionNumberResponse' do
  before do
    # run before each test
    @instance = Telstra_Messaging::ProvisionNumberResponse.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProvisionNumberResponse' do
    it 'should create an instance of ProvisionNumberResponse' do
      expect(@instance).to be_instance_of(Telstra_Messaging::ProvisionNumberResponse)
    end
  end
  describe 'test attribute "destination_address"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "expiry_date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
