# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).
require 'date'
require 'json'
require 'faraday'
require 'certifi'
require 'logging'

require_relative 'telstra_messaging_api/api_helper.rb'
require_relative 'telstra_messaging_api/telstra_messaging_api_client.rb'

# Http
require_relative 'telstra_messaging_api/http/http_call_back.rb'
require_relative 'telstra_messaging_api/http/http_client.rb'
require_relative 'telstra_messaging_api/http/http_method_enum.rb'
require_relative 'telstra_messaging_api/http/http_request.rb'
require_relative 'telstra_messaging_api/http/http_response.rb'
require_relative 'telstra_messaging_api/http/http_context.rb'
require_relative 'telstra_messaging_api/http/faraday_client.rb'
require_relative 'telstra_messaging_api/http/auth/o_auth_2.rb'

# Models
require_relative 'telstra_messaging_api/models/base_model.rb'
require_relative 'telstra_messaging_api/models/outbound_poll_response.rb'
require_relative 'telstra_messaging_api/models/mms_content.rb'
require_relative 'telstra_messaging_api/models/send_mms_request.rb'
require_relative 'telstra_messaging_api/models/error_error.rb'
require_relative 'telstra_messaging_api/models/send_sms_request.rb'
require_relative 'telstra_messaging_api/models/inbound_poll_response.rb'
require_relative 'telstra_messaging_api/models/message.rb'
require_relative 'telstra_messaging_api/models/message_sent_response.rb'
require_relative 'telstra_messaging_api/models/provision_number_response.rb'
require_relative 'telstra_messaging_api/models/provision_number_request.rb'
require_relative 'telstra_messaging_api/models/o_auth_token.rb'
require_relative 'telstra_messaging_api/models/status_enum.rb'
require_relative 'telstra_messaging_api/models/message_type_enum.rb'
require_relative 'telstra_messaging_api/models/o_auth_scope_enum.rb'
require_relative 'telstra_messaging_api/models/o_auth_provider_error_enum.rb'

# Exceptions
require_relative 'telstra_messaging_api/exceptions/api_exception.rb'
require_relative 'telstra_messaging_api/exceptions' \
                 '/error_error_error_62_error_exception.rb'
require_relative 'telstra_messaging_api/exceptions' \
                 '/error_error_error_error_error_exception.rb'
require_relative 'telstra_messaging_api/exceptions/o_auth_provider_exception.rb'

require_relative 'telstra_messaging_api/configuration.rb'

# Controllers
require_relative 'telstra_messaging_api/controllers/base_controller.rb'
require_relative 'telstra_messaging_api/controllers/provisioning_controller.rb'
require_relative 'telstra_messaging_api/controllers/messaging_controller.rb'
require_relative 'telstra_messaging_api/controllers' \
                 '/o_auth_authorization_controller.rb'
