=begin
#Telstra Messaging API

# The Telstra SMS Messaging API allows your applications to send and receive SMS text messages from Australia's leading network operator.  It also allows your application to track the delivery status of both sent and received SMS messages. 

OpenAPI spec version: 2.2.4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: unset

=end

# Common files
require 'Telstra_Messaging/api_client'
require 'Telstra_Messaging/api_error'
require 'Telstra_Messaging/version'
require 'Telstra_Messaging/configuration'

# Models
require 'Telstra_Messaging/models/delete_number_request'
require 'Telstra_Messaging/models/error_error'
require 'Telstra_Messaging/models/error_error_error'
require 'Telstra_Messaging/models/get_subscription_response'
require 'Telstra_Messaging/models/inbound_poll_response'
require 'Telstra_Messaging/models/mms_content'
require 'Telstra_Messaging/models/message'
require 'Telstra_Messaging/models/message_sent_response'
require 'Telstra_Messaging/models/message_type'
require 'Telstra_Messaging/models/o_auth_request'
require 'Telstra_Messaging/models/o_auth_response'
require 'Telstra_Messaging/models/outbound_poll_response'
require 'Telstra_Messaging/models/provision_number_request'
require 'Telstra_Messaging/models/provision_number_response'
require 'Telstra_Messaging/models/send_mms_request'
require 'Telstra_Messaging/models/send_sms_request'
require 'Telstra_Messaging/models/status'

# APIs
require 'Telstra_Messaging/api/authentication_api'
require 'Telstra_Messaging/api/messaging_api'
require 'Telstra_Messaging/api/provisioning_api'

module Telstra_Messaging
  class << self
    # Customize default settings for the SDK using block.
    #   Telstra_Messaging.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
