# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # ErrorError Model.
  class ErrorError < BaseModel
    # A short error code
    # @return [String]
    attr_accessor :status

    # Message describing the error.
    # @return [String]
    attr_accessor :message

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash['message'] = 'message'
      @_hash
    end

    def initialize(status = nil,
                   message = nil)
      @status = status
      @message = message
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash['status']
      message = hash['message']

      # Create object from extracted values.
      ErrorError.new(status,
                     message)
    end
  end
end
