# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # Poll for incoming messages returning the latest. Only works if no url was
  # specified when provisioning a number.
  class InboundPollResponse < BaseModel
    # The phone number (recipient) that the message was sent to(in
    # E.164 format).
    # @return [String]
    attr_accessor :destination_address

    # The phone number (sender) that the message was sent from (in
    # E.164 format).
    # @return [String]
    attr_accessor :sender_address

    # Text body of the message that was sent
    # @return [String]
    attr_accessor :message

    # The date and time when the message was recieved by recipient.
    # @return [String]
    attr_accessor :sent_timestamp

    # Optional message ID of the SMS you sent. Use this ID to viewthe message
    # status or get responses.
    # @return [String]
    attr_accessor :message_id

    # Message status from the server
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['destination_address'] = 'destinationAddress'
      @_hash['sender_address'] = 'senderAddress'
      @_hash['message'] = 'message'
      @_hash['sent_timestamp'] = 'sentTimestamp'
      @_hash['message_id'] = 'messageId'
      @_hash['status'] = 'status'
      @_hash
    end

    def initialize(destination_address = nil,
                   sender_address = nil,
                   message = nil,
                   sent_timestamp = nil,
                   message_id = nil,
                   status = nil)
      @destination_address = destination_address
      @sender_address = sender_address
      @message = message
      @sent_timestamp = sent_timestamp
      @message_id = message_id
      @status = status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      destination_address = hash['destinationAddress']
      sender_address = hash['senderAddress']
      message = hash['message']
      sent_timestamp = hash['sentTimestamp']
      message_id = hash['messageId']
      status = hash['status']

      # Create object from extracted values.
      InboundPollResponse.new(destination_address,
                              sender_address,
                              message,
                              sent_timestamp,
                              message_id,
                              status)
    end
  end
end
