# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # MessageType.
  class MessageTypeEnum
    MESSAGE_TYPE_ENUM = [
      # TODO: Write general description for SMS
      SMS = 'SMS'.freeze,

      # TODO: Write general description for MMS
      MMS = 'MMS'.freeze,

      # TODO: Write general description for RCS
      RCS = 'RCS'.freeze
    ].freeze
  end
end
