# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # MMSContent Model.
  class MMSContent < BaseModel
    # The following types are supported audio/amr 	audio/aac 	audio/mp3
    # 	audio/mpeg3 	audio/mpeg 	audio/mpg 	audio/wav 	audio/3gpp 	audio/mp4
    # 	image/gif 	image/jpeg 	image/jpg 	image/png 	image/bmp 	video/mpeg4
    # 	video/mp4 	video/mpeg 	video/3gpp 	video/3gp 	video/h263 	text/plain
    # 	text/x-vCard 	text/x-vCalendar
    # @return [String]
    attr_accessor :type

    # The file name to be associated with the content. Some devices
    # will display this file name with a placeholder for the content.
    # @return [String]
    attr_accessor :filename

    # The file name to be associated with the content. Some devices
    # will display this file name with a placeholder for the content.
    # @return [String]
    attr_accessor :payload

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['type'] = 'type'
      @_hash['filename'] = 'filename'
      @_hash['payload'] = 'payload'
      @_hash
    end

    def initialize(type = nil,
                   filename = nil,
                   payload = nil)
      @type = type
      @filename = filename
      @payload = payload
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      type = hash['type']
      filename = hash['filename']
      payload = hash['payload']

      # Create object from extracted values.
      MMSContent.new(type,
                     filename,
                     payload)
    end
  end
end
