# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # OAuth 2 scopes supported by the API
  class OAuthScopeEnum
    O_AUTH_SCOPE_ENUM = [
      # NSMS
      NSMS = 'NSMS'.freeze
    ].freeze
  end
end
