# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # OutboundPollResponse Model.
  class OutboundPollResponse < BaseModel
    # The phone number (recipient) the message was sent to (in E.164
    # format).
    # @return [String]
    attr_accessor :to

    # The date and time when the message was recieved by recipient.
    # @return [String]
    attr_accessor :received_timestamp

    # The date and time when the message was sent.
    # @return [String]
    attr_accessor :sent_timestamp

    # The date and time when the message was sent.
    # @return [StatusEnum]
    attr_accessor :delivery_status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['to'] = 'to'
      @_hash['received_timestamp'] = 'receivedTimestamp'
      @_hash['sent_timestamp'] = 'sentTimestamp'
      @_hash['delivery_status'] = 'deliveryStatus'
      @_hash
    end

    def initialize(to = nil,
                   received_timestamp = nil,
                   sent_timestamp = nil,
                   delivery_status = nil)
      @to = to
      @received_timestamp = received_timestamp
      @sent_timestamp = sent_timestamp
      @delivery_status = delivery_status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      to = hash['to']
      received_timestamp = hash['receivedTimestamp']
      sent_timestamp = hash['sentTimestamp']
      delivery_status = hash['deliveryStatus']

      # Create object from extracted values.
      OutboundPollResponse.new(to,
                               received_timestamp,
                               sent_timestamp,
                               delivery_status)
    end
  end
end
