# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # ProvisionNumberRequest Model.
  class ProvisionNumberRequest < BaseModel
    # TODO: Write general description for this method
    # @return [Integer]
    attr_accessor :active_days

    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :notify_url

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['active_days'] = 'activeDays'
      @_hash['notify_url'] = 'notifyURL'
      @_hash
    end

    def initialize(active_days = nil,
                   notify_url = nil)
      @active_days = active_days
      @notify_url = notify_url
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      active_days = hash['activeDays']
      notify_url = hash['notifyURL']

      # Create object from extracted values.
      ProvisionNumberRequest.new(active_days,
                                 notify_url)
    end
  end
end
