# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module TelstraMessagingApi
  # Status.
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for PEND
      PEND = 'PEND'.freeze,

      # TODO: Write general description for SENT
      SENT = 'SENT'.freeze,

      # TODO: Write general description for DELIVRD
      DELIVRD = 'DELIVRD'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'EXPIRED'.freeze,

      # TODO: Write general description for DELETED
      DELETED = 'DELETED'.freeze,

      # TODO: Write general description for UNDVBL
      UNDVBL = 'UNDVBL'.freeze,

      # TODO: Write general description for REJECTED
      REJECTED = 'REJECTED'.freeze,

      # TODO: Write general description for READ
      READ = 'READ'.freeze
    ].freeze
  end
end
